# -*- coding: utf-8 -*-
"""1.7 - Projeto 1 - Calculadoraa.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17J74PP4tvHcmTRvlQ3tQ17xOClqCuL42

#Calculadora Python - Projeto 1

##Instruções

Agora, você fará a primeira parte do seu primeiro projeto! Como disse o professor Rodrigo, não há uma forma fixa: o importante é que seu código siga uma sequência lógica e tenha, ao menos, os critérios abaixo, ok?

**Passo a passo:**

1.    Utilize o comando 'input' para receber ao menos 2 números de entrada do usuário.
2.    Converta os valores recebidos pelo usuário para número inteiro (int) ou ponto flutuante (float).
3.    Implemente ao menos 4 operações matemáticas em seu código.
4.    Adicione um laço de repetição ou uma condicional. Por exemplo: você pode permitir que o usuário escolha qual operação realizar ou criar um loop que permita ao usuário realizar várias operações consecutivas.
5.    Utilize o comando 'print' para exibir o resultado da operação matemática.

*Tempo estimado para resolução: 40 minutos*

*Como submeter sua entrega: Envie seu código em formato .ipynb. Para isso, em seu Colab, vá em arquivo > fazer download > fazer download do ipynb.*
"""

#Laço para decidir se o código deve encerrar ou fazer uma operação matemática

resposta = ""
while resposta != "sair":

  #decisão para saída ou coleta de valores
  resposta = input("Por favor, digite a operação desejada: '+', '-', '*', '/' , ou caso deseje sair, digite 'sair':")
  if resposta == "sair":
    print("Obrigado por usar a calculadora!")
    break

  #coleta de valores
  valor1 = float(input("Digite o primeiro valor: "))
  valor2 = float(input("Digite o segundo valor: "))

  #condicional para decidir qual cálculo matemático deve ser feito
  if resposta == "+":
    print(valor1 + valor2)
  elif resposta == "-":
    print(valor1 - valor2)
  elif resposta == "*":
    print(valor1 * valor2)
  elif resposta == "/":
    print(valor1 / valor2)
  else:
    print("Cálculo não executado por não ser um dos operadores escolhidos")